---
title: "Center Position: Age vs Performance"
format: pdf
---



```{r}
#age vs points

library(tidyverse)
library(ggplot2)

playerstats <- read.csv("nba-player-stats-2021.csv")

modified <-playerstats |> filter(pos == 'C') |> select(player, pos, age, mp, pts, ast, orb, drb, fgpercent, tov) |> filter(mp > 500)


cols <- c("pts", "ast", "orb", "drb", "fgpercent", "tov")

for (colname in cols) {
  modified[[colname]] <- round(modified[[colname]] / modified[["mp"]], 6)
}

modified <- head(modified, 100)

ggplot(
    data = modified,
    mapping = aes(
    x = age,
    y = pts,
    color = pos
  )
) +
geom_point() +
labs(
  x = "Age",
  y = "Points/Minute (pts/min)",
  title = "Age vs Points per Minute",
  color = "Player Position"
) + theme( plot.title = element_text(hjust = 0.5)
  )


```

```{r}
#age vs assists


ggplot(
    data = modified,
    mapping = aes(
    x = age,
    y = ast,
    color = pos
  )
) +
geom_point() +
labs(
x = "Age",
y = "Assists/Minute (ast/min)",
title = "Age vs Assists per Minute",
color = "Player Position"

) + theme( plot.title = element_text(hjust = 0.5)
  )
```


```{r}

#age vs Offensive Rebounds

ggplot(
    data = modified,
    mapping = aes(
    x = age,
    y = orb,
    color = pos
  )
) +
geom_point() +
labs(
x = "Age",
y = "Offensive Rebounds/Minute (orb/min)",
title = "Age vs Offensive Rebounds per Minute",
color = "Player Position"
) + theme( plot.title = element_text(hjust = 0.5)
  )

```


```{r}
#age vs Defensive Rebounds

ggplot(
    data = modified,
    mapping = aes(
    x = age,
    y = drb,
    color = pos
  )
) +
geom_point() +
labs(
x = "Age",
y = "Defensive Rebounds/Minute (drb/min)",
title = "Age vs Defensive Rebounds per Minute",
color = "Player Position"

) + theme( plot.title = element_text(hjust = 0.5)
  )

```

```{r}
#age vs Field Goal Percentage
ggplot(
    data = modified,
    mapping = aes(
    x = age,
    y = fgpercent,
    color = pos
  )
) +
geom_point() +
labs(
x = "Age",
y = "FG  Percentage/Minute (fg%/min)",
title = "Age vs Field Goal Percentage per Minute",
color = "Player Position"

) + theme( plot.title = element_text(hjust = 0.5)
  )

```

```{r}
#age vs Turnovers

ggplot(
    data = modified,
    mapping = aes(
    x = age,
    y = tov,
    color = pos
  )
) +
geom_point() +
labs(
x = "Age",
y = "Turnovers/Minute (tov/min)",
title = "Age vs Turnovers per Minute",
color = "Player Position"

) + theme( plot.title = element_text(hjust = 0.5)
  )

```


